### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by cliedelt** [BookingSync/ember-data-partial-model#18]
Hello,
Sorry Im very new to Emberjs.
How do I install ember-data-partial-model for an existing project?

I assume cloning the git is not the right way.

Thanks!

**Comment by Azdaroth** [comment]
Hi,

It would be `ember install ember-data-partial-model` and that's all, just like any other addon :).

**Comment by cliedelt** [comment]
Oh silly me. Thank you very much! I didnt know its so simple.

Because you are online and i know i will ask this myself in a couple of minutes:

If i allready using an Adapter could I write this:

``` javascript
export default JSONAPIAdapter.extend(PartialModelAdapter, {
//My Code
});
export default DS.RESTAdapter.extend({
    DataAdapterMixin,
    PartialModelAdapter
},
{
    authorizer: 'authorizer:custom',
    host: config.ServerIp
});
```

**Comment by Azdaroth** [comment]
Not sure what you exactly mean, but you need to add `PartialModelAdapter` as a mixin:

```
export default SomeAdapter.extend(MixinA, MixinB, PartialModelAdapter, {
 // rest of the code
});
```

**Comment by cliedelt** [comment]
Okay.. So i think i setup everything correctly.

But I get a lot of warning and on error:

```
DEPRECATION: Your custom serializer uses the old version of the Serializer API, with `extract` hooks. Please upgrade your serializers to the new Serializer API using `normalizeResponse` hooks instead. [deprecation id: ds.serializer.extract-hooks-deprecated]
        at ember$data$lib$system$store$serializer$response$$normalizeResponseHelper (http://46.101.117.220:4200/assets/vendor.js:76725:15)
        at http://46.101.117.220:4200/assets/vendor.js:78905:25
        at Object.Backburner.run (http://46.101.117.220:4200/assets/vendor.js:10843:25)
        at ember$data$lib$system$store$$Service.extend._adapterRun (http://46.101.117.220:4200/assets/vendor.js:84741:33)
        at http://46.101.117.220:4200/assets/vendor.js:78903:22
        at tryCatch (http://46.101.117.220:4200/assets/vendor.js:67710:14)
        at invokeCallback (http://46.101.117.220:4200/assets/vendor.js:67725:15)
        at publish (http://46.101.117.220:4200/assets/vendor.js:67693:9)
        at http://46.101.117.220:4200/assets/vendor.js:44051:7
ember.debug.js:5533 WARNING: Encountered "id" in payload, but no model was found for model name "id" (resolved model name using client@serializer:application:.modelNameFromPayloadKey("id"))
ember.debug.js:5533 WARNING: Encountered "user_id" in payload, but no model was found for model name "user-id" (resolved model name using client@serializer:application:.modelNameFromPayloadKey("user_id"))
ember.debug.js:5533 WARNING: Encountered "name" in payload, but no model was found for model name "name" (resolved model name using client@serializer:application:.modelNameFromPayloadKey("name"))
ember.debug.js:5533 WARNING: Encountered "created_at" in payload, but no model was found for model name "created-at" (resolved model name using client@serializer:application:.modelNameFromPayloadKey("created_at"))
ember.debug.js:5533 WARNING: Encountered "updated_at" in payload, but no model was found for model name "updated-at" (resolved model name using client@serializer:application:.modelNameFromPayloadKey("updated_at"))
ember.debug.js:5533 WARNING: Encountered "workoutItems" in payload, but no model was found for model name "workout-item" (resolved model name using client@serializer:application:.modelNameFromPayloadKey("workoutItems"))
ember.debug.js:33540 TypeError: Cannot read property '_internalModel' of undefined
    at finders.js:44
    at Object.Backburner.run (ember.debug.js:293)
    at ember$data$lib$system$store$$Service.extend._adapterRun (store.js:2049)
    at finders.js:39
    at tryCatch (ember.debug.js:57160)
    at invokeCallback (ember.debug.js:57175)
    at publish (ember.debug.js:57143)
    at ember.debug.js:33501
    at Queue.invoke (ember.debug.js:1021)
    at Object.Queue.flush (ember.debug.js:1085)
```

The complete respone would be:

```
{
    workout =     {
        "created_at" = "2015-11-12 13:18:15";
        id = 1;
        name = "Workout 001";
        "updated_at" = "2015-11-12 13:18:15";
        "user_id" = 1;
        workoutItems =         (
                        {
                "created_at" = "2015-11-12 13:18:54";
                exSets =                 (
                                        {
                        "created_at" = "2015-11-12 13:18:55";
                        id = 1;
                        setItems =                         (
                                                        {
                                "created_at" = "2015-11-12 13:18:55";
...
```

But unfortunately the response is:

``` json
{"id":5,"user_id":2,"name":"Test!","created_at":"2015-11-13 10:32:00","updated_at":"2015-11-13 10:32:00","workoutItems":[]}
```

Is there a Problem handling empty data?
I didnt know how to put these nested json in models so i simply used:
(I read it here: https://github.com/emberjs/data/issues/53 )

``` javascript
export default PartialModel.extend({
    name: attr('string'),
    user_id: DS.attr('number'),
    created_at: DS.attr('date'),
    updated_at: DS.attr('date'),

    extended: partial('workout', 'extended', {
        workoutItems: attr()
    })
});
```

Did i do it wrong? Should I create Models for e.g. workoutItems and set a relationship? Or how can I solve this?

**Comment by Azdaroth** [comment]
I think the issue is with the serializer or API response (depending on what you want to customize), serializer was expecting payload with format `{ modelName: attributes }`, in your response there are only attributes, but I guess it's safer to have models' names in response. BTW., if possible, you should try jsonapi, it solves most of the problems with payload structuring.
